### PR TITLE
Add dependencies for conda environment

### PR DESCRIPTION
**Pull request by mkuzak**
This will allow to install whole necessary conda environment in one command:
`conda env create -f environment.yml`

### CODE REVIEW

**Comment by dafnevk** [comment]
When creating an envirnoment with this yml file, I get the following error:
NoPackagesFoundError: Packages missing in current linux-64 channels: 
  - python-dateutil 2.3 py27_0
  - keras 1.0.7 py27_0
  - protobuf 3.2.0 py27_0
  - tensorflow 1.0.0 py27_0

There seems to be issues with the versions of these packages.  I created different environments for different python versions, that have exactly the package versions that work for that python version.

**Comment by mkuzak** [comment]
ah, interesting, are you using python 2.7?

**Comment by mkuzak** [comment]
seems to work for me on mac os with both 2.7 and 3
do you have conda-forge channel?

**Comment by dafnevk** [comment]
Yes, well my anaconda uses 2.7 as a default. And when creating an environment with a environment.yml file, I think it tries to match the python version with the dependencies in the file, so in this case also 2.7.

I think indeed I don't have the conda-forge channel. It's probably possible to add that to the environment.yml

**Comment by dafnevk** [comment]
Yep, It works when I add these lines to the environment.yml:
```
channels:
- conda-forge
- bioconda

```

**Pull request merged**
