### PR TITLE
Data generators Issue #211

### PR DESCRIPTION
**Pull request by bsolino**
Pull request for issue #211 

Changed the ```train_models_on_samples``` function to support both tensor slices (as it was doing before), ```tf.data.Dataset``` and generators (implemented using ```tf.keras.utils.Sequence```).

Datasets and generators may not be possible to subset.

### CODE REVIEW

**Comment by florian-huber** [comment]
Does ``Dataset.from_tensor_slices`` really help to avoid memory issues?
Or was this tested in any way?
I am only asking because from the tensorflow documentation it sounded more like we would have to use ``Dataset.from_generator`` --> https://www.tensorflow.org/guide/data#consuming_numpy_arrays

**Comment by bsolino** [comment]
Add information about this feature to the docstring.

Perhaps also mention in the tutorial?

**Comment by bsolino** [comment]
Test if passing a dataset or a generator works.

**Comment by bsolino** [comment]
> Add information about this feature to the docstring.
> 
> Perhaps also mention in the tutorial?

Solved in commit e052504

**Comment by bsolino** [comment]
Note: The weird card movements were because for some reason this card appeared in the project as "Requires triage". However, after a review the project already had the linked issue card, so this was redundant.

**Pull request merged**
